# Generated by Django 2.2.16 on 2020-10-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mileapp',
            options={'managed': False},
        ),
    ]
