# Generated by Django 2.2.16 on 2020-10-01 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mileapp', '0002_auto_20201001_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mileapp',
            options={},
        ),
    ]
