from rest_framework import serializers

from .models import Mileapp


class MileAppSerializer(serializers.Serializer):
    transaction_id = serializers.CharField(max_length=100)
    customer_name = serializers.CharField(max_length=100)
    customer_code = serializers.IntegerField()
    transaction_amount = serializers.IntegerField()
    transaction_discount = serializers.IntegerField()
    transaction_additional_field = serializers.IntegerField(allow_null=True)
    transaction_payment_type = serializers.IntegerField()
    transaction_state = serializers.CharField(max_length=100)
    transaction_code = serializers.CharField(max_length=100)
    transaction_order = serializers.IntegerField()
    location_id = serializers.CharField(max_length=100)
    organization_id = serializers.IntegerField()
    created_at = serializers.CharField(max_length=100)
    updated_at = serializers.CharField(max_length=100)
    transaction_payment_type_name = serializers.CharField(max_length=100)
    transaction_cash_amount = serializers.IntegerField()
    transaction_cash_change = serializers.IntegerField()
    customer_attribute_nama_sales = serializers.CharField(max_length=100)
    customer_attribute_top = serializers.CharField(max_length=100)
    customer_attribute_jenis_pelanggan = serializers.CharField(max_length=100)
    connote_connote_id = serializers.CharField(max_length=100)
    connote_connote_number = serializers.IntegerField()
    connote_connote_service = serializers.CharField(max_length=100)
    connote_connote_service_price = serializers.IntegerField()
    connote_connote_amount = serializers.IntegerField()
    connote_connote_code = serializers.CharField(max_length=100)
    connote_connote_booking_code = serializers.IntegerField(allow_null=True)
    connote_connote_order = serializers.IntegerField()
    connote_connote_state = serializers.CharField(max_length=100)
    connote_connote_state_id = serializers.IntegerField()
    connote_zone_code_from = serializers.CharField(max_length=100)
    connote_zone_code_to = serializers.CharField(max_length=100)
    connote_surcharge_amount = serializers.IntegerField(allow_null=True)
    connote_transaction_id = serializers.CharField(max_length=100)
    connote_actual_weight = serializers.IntegerField()
    connote_volume_weight = serializers.IntegerField()
    connote_chargeable_weight = serializers.IntegerField()
    connote_created_at = serializers.CharField(max_length=100)
    connote_updated_at = serializers.CharField(max_length=100)
    connote_organization_id = serializers.IntegerField()
    connote_location_id = serializers.CharField(max_length=100)
    connote_connote_total_package = serializers.IntegerField()
    connote_connote_surcharge_amount = serializers.IntegerField(allow_null=True)
    connote_connote_sla_day = serializers.IntegerField()
    connote_location_name = serializers.CharField(max_length=100)
    connote_location_type = serializers.CharField(max_length=100)
    connote_source_tariff_db = serializers.CharField(max_length=100)
    connote_id_source_tariff = serializers.IntegerField()
    connote_pod = serializers.IntegerField(allow_null=True)
    connote_id = serializers.CharField(max_length=100)
    origin_data_customer_name = serializers.CharField(max_length=100)
    origin_data_customer_address = serializers.CharField(max_length=100)
    origin_data_customer_email = serializers.CharField(max_length=100)
    origin_data_customer_phone = serializers.CharField(max_length=100)
    origin_data_customer_address_detail = serializers.CharField(max_length=100, allow_null=True)
    origin_data_customer_zip_code = serializers.CharField(max_length=100)
    origin_data_zone_code = serializers.CharField(max_length=100)
    origin_data_organization_id = serializers.IntegerField()
    origin_data_location_id = serializers.CharField(max_length=100)
    destination_data_customer_name = serializers.CharField(max_length=100)
    destination_data_customer_address = serializers.CharField(max_length=100)
    destination_data_customer_email = serializers.IntegerField(allow_null=True)
    destination_data_customer_phone = serializers.IntegerField()
    destination_data_customer_address_detail = serializers.CharField(max_length=100)
    destination_data_customer_zip_code = serializers.IntegerField()
    destination_data_zone_code = serializers.CharField(max_length=100)
    destination_data_organization_id = serializers.IntegerField()
    destination_data_location_id = serializers.CharField(max_length=100)
    koli_data_koli_length = serializers.IntegerField()
    koli_data_awb_url = serializers.CharField(max_length=100)
    koli_data_created_at = serializers.DateTimeField()
    koli_data_koli_chargeable_weight = serializers.IntegerField()
    koli_data_koli_width = serializers.IntegerField()
    koli_data_koli_height = serializers.IntegerField()
    koli_data_updated_at = serializers.DateTimeField()
    koli_data_koli_description = serializers.CharField(max_length=100)
    koli_data_koli_formula_id = serializers.IntegerField(allow_null=True)
    koli_data_connote_id = serializers.CharField(max_length=100)
    koli_data_koli_volume = serializers.IntegerField()
    koli_data_koli_weight = serializers.IntegerField()
    koli_data_koli_id = serializers.CharField(max_length=100)
    koli_data_koli_custom_field_awb_sicepat = serializers.IntegerField(allow_null=True)
    koli_data_koli_custom_field_harga_barang = serializers.IntegerField(allow_null=True)
    koli_data_koli_code = serializers.CharField(max_length=100)
    custom_field_catatan_tambahan = serializers.CharField(max_length=100, allow_null=True)
    currentlocation_name = serializers.CharField(max_length=100, allow_null=True)
    currentlocation_code = serializers.CharField(max_length=100, allow_null=True)
    currentlocation_type = serializers.CharField(max_length=100, allow_null=True)

    def create(self, validated_data):
        return Mileapp.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.transaction_id = validated_data.get('transaction_id', instance.transaction_id)
        instance.customer_name = validated_data.get('customer_name', instance.customer_name)
        instance.customer_code = validated_data.get('customer_code', instance.customer_code)
        instance.transaction_amount = validated_data.get('transaction_amount', instance.transaction_amount)
        instance.transaction_discount = validated_data.get('transaction_discount', instance.transaction_discount)
        instance.transaction_additional_field = validated_data.get('transaction_additional_field', instance.transaction_additional_field)
        instance.transaction_payment_type = validated_data.get('transaction_payment_type', instance.transaction_payment_type)
        instance.transaction_state = validated_data.get('transaction_state', instance.transaction_state)
        instance.transaction_code = validated_data.get('transaction_code', instance.transaction_code)
        instance.transaction_order = validated_data.get('transaction_order', instance.transaction_order)
        instance.location_id = validated_data.get('location_id', instance.location_id)
        instance.organization_id = validated_data.get('organization_id', instance.organization_id)
        instance.created_at = validated_data.get('created_at', instance.created_at)
        instance.updated_at = validated_data.get('updated_at', instance.updated_at)
        instance.transaction_payment_type_name = validated_data.get('transaction_payment_type_name', instance.transaction_payment_type_name)
        instance.transaction_cash_amount = validated_data.get('transaction_cash_amount', instance.transaction_cash_amount)
        instance.transaction_cash_change = validated_data.get('transaction_cash_change', instance.transaction_cash_change)
        instance.customer_attribute_nama_sales = validated_data.get('customer_attribute_nama_sales', instance.customer_attribute_nama_sales)
        instance.customer_attribute_top = validated_data.get('customer_attribute_top', instance.customer_attribute_top)
        instance.customer_attribute_jenis_pelanggan = validated_data.get('customer_attribute_jenis_pelanggan', instance.customer_attribute_jenis_pelanggan)
        instance.connote_connote_id = validated_data.get('connote_connote_id', instance.connote_connote_id)
        instance.connote_connote_number = validated_data.get('connote_connote_number', instance.connote_connote_number)
        instance.connote_connote_service = validated_data.get('connote_connote_service', instance.transaction_id)
        instance.connote_connote_service_price = validated_data.get('connote_connote_service_price', instance.connote_connote_service_price)
        instance.connote_connote_amount = validated_data.get('connote_connote_amount', instance.connote_connote_amount)
        instance.connote_connote_code = validated_data.get('connote_connote_code', instance.connote_connote_code)
        instance.connote_connote_booking_code = validated_data.get('connote_connote_booking_code', instance.connote_connote_booking_code)
        instance.connote_connote_order = validated_data.get('connote_connote_order', instance.connote_connote_order)
        instance.connote_connote_state = validated_data.get('connote_connote_state', instance.connote_connote_state)
        instance.connote_connote_state_id = validated_data.get('connote_connote_state_id', instance.connote_connote_state_id)
        instance.connote_zone_code_from = validated_data.get('connote_zone_code_from', instance.connote_zone_code_from)
        instance.connote_zone_code_to = validated_data.get('connote_zone_code_to', instance.connote_zone_code_to)
        instance.connote_surcharge_amount = validated_data.get('connote_surcharge_amount', instance.connote_surcharge_amount)
        instance.connote_transaction_id = validated_data.get('connote_transaction_id', instance.connote_transaction_id)
        instance.connote_actual_weight = validated_data.get('connote_actual_weight', instance.connote_actual_weight)
        instance.connote_volume_weight = validated_data.get('connote_volume_weight', instance.connote_volume_weight)
        instance.connote_chargeable_weight = validated_data.get('connote_chargeable_weight', instance.connote_chargeable_weight)
        instance.connote_created_at = validated_data.get('connote_created_at', instance.connote_created_at)
        instance.connote_updated_at = validated_data.get('connote_updated_at', instance.connote_updated_at)
        instance.connote_organization_id = validated_data.get('connote_organization_id', instance.connote_organization_id)
        instance.connote_location_id = validated_data.get('connote_location_id', instance.connote_location_id)
        instance.connote_connote_total_package = validated_data.get('connote_connote_total_package', instance.connote_connote_total_package)
        instance.connote_connote_surcharge_amount = validated_data.get('connote_connote_surcharge_amount', instance.connote_connote_surcharge_amount)
        instance.connote_connote_sla_day = validated_data.get('connote_connote_sla_day', instance.connote_connote_sla_day)
        instance.connote_location_name = validated_data.get('connote_location_name', instance.connote_location_name)
        instance.connote_location_type = validated_data.get('connote_location_type', instance.connote_location_type)
        instance.connote_source_tariff_db = validated_data.get('connote_source_tariff_db', instance.connote_source_tariff_db)
        instance.connote_id_source_tariff = validated_data.get('connote_id_source_tariff', instance.connote_id_source_tariff)
        instance.connote_pod = validated_data.get('connote_pod', instance.connote_pod)
        instance.connote_id = validated_data.get('connote_id', instance.connote_id)
        instance.origin_data_customer_name = validated_data.get('origin_data_customer_name', instance.origin_data_customer_name)
        instance.origin_data_customer_address = validated_data.get('origin_data_customer_address', instance.origin_data_customer_address)
        instance.origin_data_customer_email = validated_data.get('origin_data_customer_email', instance.origin_data_customer_email)
        instance.origin_data_customer_phone = validated_data.get('origin_data_customer_phone', instance.origin_data_customer_phone)
        instance.origin_data_customer_address_detail = validated_data.get('origin_data_customer_address_detail', instance.origin_data_customer_address_detail)
        instance.origin_data_customer_zip_code = validated_data.get('origin_data_customer_zip_code', instance.origin_data_customer_zip_code)
        instance.origin_data_zone_code = validated_data.get('origin_data_zone_code', instance.origin_data_zone_code)
        instance.origin_data_organization_id = validated_data.get('origin_data_organization_id', instance.origin_data_organization_id)
        instance.origin_data_location_id = validated_data.get('origin_data_location_id', instance.origin_data_location_id)
        instance.destination_data_customer_name = validated_data.get('destination_data_customer_name', instance.destination_data_customer_name)
        instance.destination_data_customer_address = validated_data.get('destination_data_customer_address', instance.destination_data_customer_address)
        instance.destination_data_customer_address = validated_data.get('destination_data_customer_address', instance.destination_data_customer_address)
        instance.destination_data_customer_phone = validated_data.get('destination_data_customer_phone', instance.destination_data_customer_phone)
        instance.destination_data_customer_address_detail = validated_data.get('destination_data_customer_address_detail', instance.destination_data_customer_address_detail)
        instance.destination_data_customer_zip_code = validated_data.get('destination_data_customer_zip_code', instance.destination_data_customer_zip_code)
        instance.destination_data_zone_code = validated_data.get('destination_data_zone_code', instance.destination_data_zone_code)
        instance.destination_data_organization_id = validated_data.get('destination_data_organization_id', instance.destination_data_organization_id)
        instance.destination_data_location_id = validated_data.get('destination_data_location_id', instance.destination_data_location_id)
        instance.koli_data_koli_length = validated_data.get('koli_data_koli_length', instance.koli_data_koli_length)
        instance.koli_data_awb_url = validated_data.get('koli_data_awb_url', instance.koli_data_awb_url)
        instance.koli_data_created_at = validated_data.get('koli_data_created_at', instance.koli_data_created_at)
        instance.koli_data_koli_chargeable_weight = validated_data.get('koli_data_koli_chargeable_weight', instance.koli_data_koli_chargeable_weight)
        instance.koli_data_koli_width = validated_data.get('koli_data_koli_width', instance.koli_data_koli_width)
        instance.koli_data_koli_height = validated_data.get('koli_data_koli_height', instance.koli_data_koli_height)
        instance.koli_data_updated_at = validated_data.get('koli_data_updated_at', instance.koli_data_updated_at)
        instance.koli_data_koli_description = validated_data.get('koli_data_koli_description', instance.koli_data_koli_description)
        instance.koli_data_koli_formula_id = validated_data.get('koli_data_koli_formula_id', instance.koli_data_koli_formula_id)
        instance.koli_data_connote_id = validated_data.get('koli_data_connote_id', instance.koli_data_connote_id)
        instance.koli_data_koli_volume = validated_data.get('koli_data_koli_volume', instance.koli_data_koli_volume)
        instance.koli_data_koli_weight = validated_data.get('koli_data_koli_weight', instance.koli_data_koli_weight)
        instance.koli_data_koli_id = validated_data.get('koli_data_koli_id', instance.koli_data_koli_id)
        instance.koli_data_koli_custom_field_awb_sicepat = validated_data.get('koli_data_koli_custom_field_awb_sicepat', instance.koli_data_koli_custom_field_awb_sicepat)
        instance.koli_data_koli_custom_field_harga_barang = validated_data.get('koli_data_koli_custom_field_harga_barang', instance.koli_data_koli_custom_field_harga_barang)
        instance.koli_data_koli_code = validated_data.get('koli_data_koli_code', instance.koli_data_koli_code)
        instance.custom_field_catatan_tambahan = validated_data.get('custom_field_catatan_tambahan', instance.custom_field_catatan_tambahan)
        instance.currentlocation_name = validated_data.get('currentlocation_name', instance.currentlocation_name)
        instance.currentlocation_code = validated_data.get('currentlocation_code', instance.currentlocation_code)
        instance.currentlocation_type = validated_data.get('currentlocation_type', instance.currentlocation_type)

        instance.save()
        return instance
