const dataToSend = {
    "new_data":{
        "connote_organization_id": 6,
        "connote_connote_number": 1,
        "connote_connote_state_id": 2,
        "koli_data_koli_custom_field_awb_sicepat": null,
        "connote_connote_order": 326931,
        "connote_connote_booking_code": null,
        "origin_data_customer_name": "PT. NARA OKA PRAKARSA",
        "connote_volume_weight": 0,
        "koli_data_connote_id": "f70670b1-c3ef-4caf-bc4f-eefa702092ed",
        "koli_data_koli_formula_id": null,
        "origin_data_organization_id": 6,
        "connote_connote_id": "f70670b1-c3ef-4caf-bc4f-eefa702092ed",
        "destination_data_customer_phone": 248453499,
        "connote_zone_code_from": "CGKFT",
        "transaction_order": 121,
        "connote_connote_code": "AWB00100209082020",
        "location_id": "5cecb20b6c49615b174c3e74",
        "connote_surcharge_amount": null,
        "origin_data_customer_phone": "024-1234567",
        "customer_attribute_nama_sales": "Radit Fitrawikarsa",
        "destination_data_customer_address": "JL. KH. AHMAD DAHLAN NO. 01, SEMARANG TENGAH",
        "destination_data_customer_zip_code": 50241,
        "koli_data_awb_url": "https://tracking.mile.app/label/AWB00100209082020.1",
        "destination_data_customer_name": "PT AMARIS HOTEL SIMPANG LIMA",
        "connote_connote_total_package": 3,
        "koli_data_koli_code": "AWB00100209082020.1",
        "id": 3,
        "koli_data_koli_volume": 0,
        "koli_data_created_at": "2020-07-15T04:11:13Z",
        "customer_attribute_jenis_pelanggan": "B2B",
        "currentlocation_type": null,
        "updated_at": "2020-07-15T11:11:22+0700",
        "custom_field_catatan_tambahan": null,
        "destination_data_zone_code": "SMG",
        "koli_data_koli_height": 0,
        "connote_connote_service_price": 70700,
        "koli_data_koli_description": "V WARP",
        "origin_data_customer_address": "JL. KH. AHMAD DAHLAN NO. 100, SEMARANG TENGAH 12420",
        "transaction_cash_change": 0,
        "connote_zone_code_to": "SMG",
        "customer_name": "PT. AMARA PRIMATIGA",
        "currentlocation_code": null,
        "transaction_code": "CGKFT20200715121",
        "connote_created_at": "2020-07-15T11:11:12+0700",
        "connote_connote_surcharge_amount": 0,
        "customer_attribute_top": "14 Hari",
        "destination_data_location_id": "5cecb20b6c49615b174c3e74",
        "transaction_amount": 70700,
        "koli_data_updated_at": "2020-07-15T04:11:13Z",
        "created_at": "2020-07-15T11:11:12+0700",
        "transaction_discount": 0,
        "transaction_cash_amount": 0,
        "connote_chargeable_weight": 20,
        "connote_connote_service": "ECO",
        "connote_connote_state": "PAID",
        "organization_id": 6,
        "transaction_id": "d0090c40-539f-479a-8274-899b9970bddc",
        "origin_data_zone_code": "CGKFT",
        "koli_data_koli_width": 0,
        "connote_pod": null,
        "destination_data_customer_address_detail": "KOTA SEMARANG SEMARANG TENGAH KARANGKIDUL",
        "origin_data_customer_address_detail": null,
        "destination_data_organization_id": 6,
        "origin_data_location_id": "5cecb20b6c49615b174c3e74",
        "transaction_payment_type": 29,
        "customer_code": 1678593,
        "connote_updated_at": "2020-07-15T11:11:22+0700",
        "transaction_state": "PAID",
        "koli_data_koli_weight": 9,
        "koli_data_koli_chargeable_weight": 9,
        "origin_data_customer_zip_code": 12420,
        "transaction_payment_type_name": "Invoice",
        "connote_transaction_id": "d0090c40-539f-479a-8274-3479847394",
        "connote_location_type": "HUB",
        "connote_actual_weight": 20,
        "origin_data_customer_email": "info@naraoka.co.id",
        "connote_connote_amount": 70700,
        "connote_id": "f70670b1-c3ef-4caf-bc4f-eefa702092ed",
        "koli_data_koli_custom_field_harga_barang": null,
        "connote_location_name": "Hub Jakarta Selatan",
        "transaction_additional_field": null,
        "koli_data_koli_length": 0,
        "connote_location_id": "5cecb20b6c49615b174c3e74",
        "connote_source_tariff_db": "tariff_customers",
        "connote_id_source_tariff": 1576868,
        "currentlocation_name": null,
        "connote_connote_sla_day": 4,
        "koli_data_koli_id": "e2cb6d86-0bb9-409b-a1f0-389ed4f2df2d",
        "destination_data_customer_email": null
    }
}

const updateData = {
    "update_data": {
        "connote_organization_id": 6,
        "connote_connote_number": 1,
        "connote_connote_state_id": 2,
        "koli_data_koli_custom_field_awb_sicepat": null,
        "connote_connote_order": 326931,
        "connote_connote_booking_code": null,
        "origin_data_customer_name": "PT. NARA OKA PRAKARSA",
        "connote_volume_weight": 0,
        "koli_data_connote_id": "f70670b1-c3ef-4caf-bc4f-eefa702092ed",
        "koli_data_koli_formula_id": null,
        "origin_data_organization_id": 6,
        "connote_connote_id": "f70670b1-c3ef-4caf-bc4f-eefa702092ed",
        "destination_data_customer_phone": 248453499,
        "connote_zone_code_from": "CGKFT",
        "transaction_order": 121,
        "connote_connote_code": "AWB00100209082020",
        "location_id": "5cecb20b6c49615b174c3e74",
        "connote_surcharge_amount": null,
        "origin_data_customer_phone": "024-1234567",
        "customer_attribute_nama_sales": "Radit Fitrawikarsa",
        "destination_data_customer_address": "JL. KH. AHMAD DAHLAN NO. 01, SEMARANG TENGAH",
        "destination_data_customer_zip_code": 50241,
        "koli_data_awb_url": "https://tracking.mile.app/label/AWB00100209082020.1",
        "destination_data_customer_name": "PT AMARIS HOTEL SIMPANG LIMA",
        "connote_connote_total_package": 3,
        "koli_data_koli_code": "AWB00100209082020.1",
        "id": 3,
        "koli_data_koli_volume": 0,
        "koli_data_created_at": "2020-07-15T04:11:13Z",
        "customer_attribute_jenis_pelanggan": "B2B",
        "currentlocation_type": null,
        "updated_at": "2020-07-15T11:11:22+0700",
        "custom_field_catatan_tambahan": null,
        "destination_data_zone_code": "SMG",
        "koli_data_koli_height": 0,
        "connote_connote_service_price": 70700,
        "koli_data_koli_description": "V WARP",
        "origin_data_customer_address": "JL. KH. AHMAD DAHLAN NO. 100, SEMARANG TENGAH 12420",
        "transaction_cash_change": 0,
        "connote_zone_code_to": "SMG",
        "customer_name": "PT. AMARA PRIMATIGA",
        "currentlocation_code": null,
        "transaction_code": "CGKFT20200715121",
        "connote_created_at": "2020-07-15T11:11:12+0700",
        "connote_connote_surcharge_amount": 0,
        "customer_attribute_top": "14 Hari",
        "destination_data_location_id": "5cecb20b6c49615b174c3e74",
        "transaction_amount": 70700,
        "koli_data_updated_at": "2020-07-15T04:11:13Z",
        "created_at": "2020-07-15T11:11:12+0700",
        "transaction_discount": 0,
        "transaction_cash_amount": 0,
        "connote_chargeable_weight": 20,
        "connote_connote_service": "ECO",
        "connote_connote_state": "PAID",
        "organization_id": 6,
        "transaction_id": "d0090c40-539f-479a-8274-899b9970bddc",
        "origin_data_zone_code": "CGKFT",
        "koli_data_koli_width": 0,
        "connote_pod": null,
        "destination_data_customer_address_detail": "KOTA SEMARANG SEMARANG TENGAH KARANGKIDUL",
        "origin_data_customer_address_detail": null,
        "destination_data_organization_id": 6,
        "origin_data_location_id": "5cecb20b6c49615b174c3e74",
        "transaction_payment_type": 29,
        "customer_code": 1678593,
        "connote_updated_at": "2020-07-15T11:11:22+0700",
        "transaction_state": "PAID",
        "koli_data_koli_weight": 9,
        "koli_data_koli_chargeable_weight": 9,
        "origin_data_customer_zip_code": 12420,
        "transaction_payment_type_name": "Invoice",
        "connote_transaction_id": "d0090c40-539f-479a-8274-3479847394",
        "connote_location_type": "HUB",
        "connote_actual_weight": 20,
        "origin_data_customer_email": "info@naraoka.co.id",
        "connote_connote_amount": 70700,
        "connote_id": "f70670b1-c3ef-4caf-bc4f-eefa702092ed",
        "koli_data_koli_custom_field_harga_barang": null,
        "connote_location_name": "Hub Jakarta Selatan",
        "transaction_additional_field": null,
        "koli_data_koli_length": 0,
        "connote_location_id": "5cecb20b6c49615b174c3e74",
        "connote_source_tariff_db": "tariff_customers",
        "connote_id_source_tariff": 1576868,
        "currentlocation_name": null,
        "connote_connote_sla_day": 4,
        "koli_data_koli_id": "e2cb6d86-0bb9-409b-a1f0-389ed4f2df2d",
        "destination_data_customer_email": null
    }
}

const updateSomeColumn = {
    "update_data" : {
        "customer_name": "PT.TESTING SELURUH INDONESIA",
        "transaction_amount": "1000000"
    }
}

module.exports = {dataToSend, updateData, updateSomeColumn}
